name: backend
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  leto: ^0.0.1-dev.2
  leto_schema: ^0.0.1-dev.6
  leto_shelf: ^0.0.1-dev.2
  mongo_dart: ^0.10.5
  dotenv: ^4.2.0
  shelf: ^1.4.2

dev_dependencies:
  build_runner: ^2.4.13
  dart_frog_lint: ^0.1.0
  leto_generator: ^0.0.1-dev.4
  mocktail: ^1.0.3
  test: ^1.25.5
